SAMPLE_QUESTIONS = [
    {
        "id": 0,
        "title": "What is the meaning of life ?",
        "view_number": 1,
        "vote_number": 3,
        "description": "From ancient times the humans and ducks where asking this question...",
    },
    {
        "id": 1,
        "title": "Why did the chicken cross the road ?",
        "view_number": 5,
        "vote_number": 7,
        "description": "The questions which ponders every chicken's mind...",
    },
    {
        "id": 3,
        "title": "Who came first, the egg or the chicken ?",
        "view_number": 5,
        "vote_number": 67,
        "description": "To this day the question remains un-answered",
    },
    {
        "id": 4,
        "title": "How many programmers do you need to change a light bulb ?",
        "view_number": 8,
        "vote_number": 12,
        "description": "That darn refrigerator light is out again",
    },
    {
        "id": 5,
        "title": "How many screws does the Eiffel Tower have ?",
        "view_number": 42,
        "vote_number": 3,
        "description": "Take from last night's pub quiz",
    },
    {
        "id": 6,
        "title": "What are the winning lottery numbers for tonight's grand prize ?",
        "view_number": 23,
        "vote_number": 47,
        "description": "The prize is 1e234 euros !",
    },
    {
        "id": 7,
        "title": "If a man talks when he is alone, is he still wrong ?",
        "view_number": 82,
        "vote_number": 33,
        "description": "Adapted from the question 'if a tree falls and no one is there to hear, does it still make a sound ?'",
    },
    {
        "id": 8,
        "title": "How many chickens would it take to be able to kill a lion?",
        "view_number": 72,
        "vote_number": 0,
        "description": "In case a lion attacks you while you are walking your dog in the park",
    },
    {
        "id": 9,
        "title": "If roses are red, why are violets blue?",
        "view_number": 2,
        "vote_number": 8,
        "description": "Was asked today by my son and did not know what to answer",
    },
    {
        "id": 10,
        "title": "What do you call a male lady bug?",
        "view_number": 9,
        "vote_number": 23,
        "description": "I did not find anything on wikipedia",
    },
]
